### ISSUE TITLE
Xcarriage3.1.stl    missing from printed parts

### ISSUE THREAD

**Issue by T3DT** [Mowi/MowiPrinter#2]
the Xcarriage3.1.stl    is missing from the printed parts I  have built both versions so far... 
On the reprap Wiki you also forgot to mention the Xcarridge part as essential.. 

please add an email contact,, as there are some other points not strictly issues..with the build

**Comment by Mowi** [comment]
Sorry, I added it today. my email is info@mowidesign.com
